# Generated by Django 5.2.4 on 2025-10-10 12:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryMst',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=50, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_flag', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'CountryMst',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('status_flag', models.IntegerField(default=1)),
                ('color', models.CharField(max_length=200, null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='MstRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=20)),
                ('role_code', models.CharField(max_length=20, unique=True)),
                ('status_flag', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='StateMst',
            fields=[
                ('states_id', models.AutoField(primary_key=True, serialize=False)),
                ('states_name', models.CharField(max_length=50)),
                ('states_code', models.CharField(max_length=50, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_flag', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'StateMst',
            },
        ),
        migrations.CreateModel(
            name='CityMst',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50)),
                ('city_code', models.CharField(max_length=50, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_flag', models.IntegerField(default=1)),
                ('state_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fwc.statemst')),
            ],
            options={
                'db_table': 'CityMst',
            },
        ),
        migrations.CreateModel(
            name='MstUserLogins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('fide_id', models.IntegerField(null=True, unique=True)),
                ('age', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=500, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('loginname', models.CharField(max_length=20)),
                ('securepassword', models.CharField(max_length=200, null=True)),
                ('cityid', models.IntegerField(null=True)),
                ('stateid', models.IntegerField(null=True)),
                ('mobilenumber', models.CharField(max_length=15, null=True)),
                ('deactivated_by', models.IntegerField(null=True)),
                ('status_flag', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEPARTED', 'Departed'), ('KNOCKED_OUT', 'Knocked Out')], default='ACTIVE', max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('deactivated_on', models.DateTimeField(null=True)),
                ('last_log_id', models.IntegerField(null=True)),
                ('profile_pic', models.CharField(max_length=100, null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('countryid', models.ForeignKey(db_column='countryid', on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.countrymst')),
                ('roleid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fwc.mstrole')),
            ],
            options={
                'db_table': 'UserLogins',
                'unique_together': {('loginname',)},
            },
        ),
    ]
