# Generated by Django 5.2.4 on 2025-10-12 12:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryMst',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=50, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_flag', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'CountryMst',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('status_flag', models.IntegerField(default=1)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='MstRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=20)),
                ('role_code', models.CharField(max_length=20, unique=True)),
                ('status_flag', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='PlayerComplaint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('status_flag', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'PlayerComplaint',
            },
        ),
        migrations.CreateModel(
            name='StateMst',
            fields=[
                ('states_id', models.AutoField(primary_key=True, serialize=False)),
                ('states_name', models.CharField(max_length=50)),
                ('states_code', models.CharField(max_length=50, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_flag', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'StateMst',
            },
        ),
        migrations.CreateModel(
            name='TransportationType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('status_flag', models.IntegerField(default=1)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'TransportationType',
            },
        ),
        migrations.CreateModel(
            name='MstUserLogins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('loginname', models.CharField(max_length=20)),
                ('securepassword', models.CharField(max_length=200, null=True)),
                ('mobilenumber', models.CharField(max_length=15, null=True)),
                ('deactivated_by', models.IntegerField(null=True)),
                ('status_flag', models.IntegerField(default=1)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('deactivated_on', models.DateTimeField(null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('countryid', models.ForeignKey(db_column='countryId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.countrymst')),
                ('department', models.ForeignKey(db_column='departmentId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.department')),
                ('roleid', models.ForeignKey(db_column='roleId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.mstrole')),
            ],
            options={
                'db_table': 'UserLogins',
                'unique_together': {('loginname',)},
            },
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(null=True)),
                ('status_flag', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.mstuserlogins')),
            ],
            options={
                'db_table': 'Announcements',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('documents', models.FileField(blank=True, null=True, upload_to='player_documents/')),
                ('fide_id', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=500, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('loginname', models.CharField(max_length=20)),
                ('securepassword', models.CharField(max_length=200, null=True)),
                ('cityid', models.IntegerField(null=True)),
                ('stateid', models.IntegerField(null=True)),
                ('mobilenumber', models.CharField(max_length=15, null=True)),
                ('deactivated_by', models.IntegerField(null=True)),
                ('status_flag', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEPARTED', 'Departed'), ('KNOCKED_OUT', 'Knocked Out')], default='ACTIVE', max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('deactivated_on', models.DateTimeField(null=True)),
                ('last_log_id', models.IntegerField(null=True)),
                ('profile_pic', models.CharField(max_length=100, null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('details', models.TextField(null=True)),
                ('room_cleaning_preference', models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening')], max_length=15, null=True)),
                ('countryid', models.ForeignKey(db_column='countryId', on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.countrymst')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'db_table': 'Players',
                'unique_together': {('email',)},
            },
        ),
        migrations.CreateModel(
            name='PlayerComplaintConversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_flag', models.IntegerField(default=1)),
                ('complaint', models.ForeignKey(db_column='complaintId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='conversations', to='fwc.playercomplaint')),
                ('sender_user', models.ForeignKey(blank=True, db_column='senderUserId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.mstuserlogins')),
                ('sender_player', models.ForeignKey(blank=True, db_column='senderPlayerId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.players')),
            ],
            options={
                'db_table': 'PlayerComplaintConversation',
            },
        ),
        migrations.AddField(
            model_name='playercomplaint',
            name='player',
            field=models.ForeignKey(db_column='playerId', on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.players'),
        ),
        migrations.CreateModel(
            name='CityMst',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50)),
                ('city_code', models.CharField(max_length=50, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_flag', models.IntegerField(default=1)),
                ('state_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.statemst')),
            ],
            options={
                'db_table': 'CityMst',
            },
        ),
        migrations.CreateModel(
            name='PlayerTransportationDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_location', models.CharField(max_length=500)),
                ('drop_location', models.CharField(max_length=500)),
                ('details', models.CharField(max_length=500)),
                ('remarks', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('IN_TRANSIT', 'In Transit'), ('COMPLETED', 'Completed'), ('PENDING', 'Pending')], default='IN_TRANSIT', max_length=20)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('playerId', models.ForeignKey(db_column='playerId', on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.players')),
                ('transportationTypeId', models.ForeignKey(db_column='transportationTypeId', on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.transportationtype')),
            ],
            options={
                'db_table': 'PlayerTransportationDetails',
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity_logs', to='fwc.players')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity_logs', to='fwc.mstuserlogins')),
            ],
            options={
                'db_table': 'user_activity_log',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRecipients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sent_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_flag', models.IntegerField(default=1)),
                ('announcement', models.ForeignKey(db_column='announcementId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipients', to='fwc.announcements')),
                ('player', models.ForeignKey(db_column='playerId', on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.players')),
            ],
            options={
                'db_table': 'AnnouncementRecipients',
                'unique_together': {('announcement', 'player')},
            },
        ),
    ]
