# Generated by Django 5.2.4 on 2025-10-12 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FideIDMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fide_id', models.CharField(max_length=100, null=True)),
                ('player_name', models.CharField(max_length=100, null=True)),
                ('Full_country_name', models.CharField(max_length=100, null=True)),
                ('Short_country_name', models.CharField(max_length=20, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_flag', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'FideIDMst',
            },
        ),
    ]
