# Generated by Django 5.2.4 on 2025-10-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='color',
        ),
    ]
