# Generated by Django 5.2.4 on 2025-10-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0002_fideidmst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fideidmst',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
