# Generated by Django 5.2.4 on 2025-10-10 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0002_remove_department_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstuserlogins',
            name='roleid',
            field=models.ForeignKey(db_column='roleid', null=True, on_delete=django.db.models.deletion.CASCADE, to='fwc.mstrole'),
        ),
    ]
