# Generated by Django 5.2.4 on 2025-10-12 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0003_alter_fideidmst_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRegistrationAuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player_id', models.IntegerField(blank=True, help_text='ID of the player if registration was successful', null=True)),
                ('image', models.CharField(blank=True, help_text='Image file path', max_length=500, null=True)),
                ('documents', models.CharField(blank=True, help_text='Document file path', max_length=500, null=True)),
                ('fide_id', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('loginname', models.CharField(blank=True, max_length=20, null=True)),
                ('securepassword', models.CharField(blank=True, max_length=200, null=True)),
                ('cityid', models.IntegerField(blank=True, null=True)),
                ('stateid', models.IntegerField(blank=True, null=True)),
                ('countryid', models.IntegerField(blank=True, help_text='Country ID from CountryMst', null=True)),
                ('mobilenumber', models.CharField(blank=True, max_length=15, null=True)),
                ('deactivated_by', models.IntegerField(blank=True, null=True)),
                ('status_flag', models.IntegerField(default=1)),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('DEPARTED', 'Departed'), ('KNOCKED_OUT', 'Knocked Out')], default='ACTIVE', max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('deactivated_on', models.DateTimeField(blank=True, null=True)),
                ('last_log_id', models.IntegerField(blank=True, null=True)),
                ('profile_pic', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('room_cleaning_preference', models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening')], max_length=15, null=True)),
                ('food_allergies', models.TextField(blank=True, help_text='Food allergies information from form', null=True)),
                ('document_file_name', models.CharField(blank=True, help_text='Original name of uploaded document', max_length=255, null=True)),
                ('document_file_size', models.BigIntegerField(blank=True, help_text='Size of uploaded document in bytes', null=True)),
                ('submission_data', models.JSONField(default=dict, help_text='Raw form submission data')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('submission_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('VALIDATION_ERROR', 'Validation Error'), ('DUPLICATE', 'Duplicate')], default='SUCCESS', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if submission failed', null=True)),
                ('validation_errors', models.JSONField(default=dict, help_text='Form validation errors if any')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Player Registration Audit Log',
                'verbose_name_plural': 'Player Registration Audit Logs',
                'db_table': 'PlayerRegistrationAuditLog',
            },
        ),
    ]
