# Generated by Django 5.2.4 on 2025-10-10 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0003_alter_mstuserlogins_roleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstuserlogins',
            name='department',
            field=models.ForeignKey(db_column='departmentId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.department'),
        ),
        migrations.AlterField(
            model_name='mstuserlogins',
            name='countryid',
            field=models.ForeignKey(db_column='countryId', on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.countrymst'),
        ),
        migrations.AlterField(
            model_name='mstuserlogins',
            name='roleid',
            field=models.ForeignKey(db_column='roleId', null=True, on_delete=django.db.models.deletion.CASCADE, to='fwc.mstrole'),
        ),
    ]
