# Generated by Django 5.2.4 on 2025-10-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0004_playerregistrationauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertransportationdetails',
            name='status',
            field=models.CharField(choices=[('ARRIVED_AIRPORT', 'Arrived at Airport'), ('ENTROUTE_HOTEL', 'Entroute to Hotel'), ('REACHED_HOTEL', 'Reached Hotel'), ('IN_TRANSIT', 'In Transit'), ('REACHED_DESTINATION', 'Reached Destination'), ('DEPARTED_AIRPORT', 'Departed for Airport'), ('REACHED_AIRPORT_DEPARTURE', 'Reached Airport for Departure')], default='IN_TRANSIT', max_length=200),
        ),
    ]
