# Generated by Django 5.2.4 on 2025-10-10 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0004_mstuserlogins_department_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mstuserlogins',
            unique_together=set(),
        ),
    ]
