# Generated by Django 5.2.4 on 2025-10-13 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0005_alter_playertransportationdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='is_self_registered',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='playerregistrationauditlog',
            name='room_cleaning_preference',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening'), ('AT_HOTEL', 'At Hotel')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='countryid',
            field=models.ForeignKey(db_column='countryId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.countrymst'),
        ),
        migrations.AlterField(
            model_name='players',
            name='room_cleaning_preference',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening'), ('AT_HOTEL', 'At Hotel')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DEPARTED', 'Departed'), ('KNOCKED_OUT', 'Knocked Out')], default='ACTIVE', max_length=50, null=True),
        ),
    ]
