# Generated by Django 5.2.4 on 2025-10-11 09:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0005_alter_mstuserlogins_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mstuserlogins',
            name='fide_id',
        ),
        migrations.RemoveField(
            model_name='mstuserlogins',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mstuserlogins',
            name='status',
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('fide_id', models.IntegerField(null=True, unique=True)),
                ('age', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=500, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('loginname', models.CharField(max_length=20)),
                ('securepassword', models.CharField(max_length=200, null=True)),
                ('cityid', models.IntegerField(null=True)),
                ('stateid', models.IntegerField(null=True)),
                ('mobilenumber', models.CharField(max_length=15, null=True)),
                ('deactivated_by', models.IntegerField(null=True)),
                ('status_flag', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEPARTED', 'Departed'), ('KNOCKED_OUT', 'Knocked Out')], default='ACTIVE', max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('deactivated_on', models.DateTimeField(null=True)),
                ('last_log_id', models.IntegerField(null=True)),
                ('profile_pic', models.CharField(max_length=100, null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('countryid', models.ForeignKey(db_column='countryId', on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.countrymst')),
            ],
            options={
                'db_table': 'Players',
                'unique_together': {('email',)},
            },
        ),
    ]
