# Generated by Django 5.2.4 on 2025-10-11 13:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0006_remove_mstuserlogins_fide_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportationType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('status_flag', models.IntegerField(default=1)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'TransportationType',
            },
        ),
        migrations.CreateModel(
            name='PlayerTransportationDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_location', models.CharField(max_length=500)),
                ('drop_location', models.CharField(max_length=500)),
                ('details', models.CharField(max_length=500)),
                ('remarks', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('IN_TRANSIT', 'In Transit'), ('COMPLETED', 'Completed'), ('PENDING', 'Pending')], default='IN_TRANSIT', max_length=20)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('playerId', models.ForeignKey(db_column='playerId', on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.players')),
                ('transportationTypeId', models.ForeignKey(db_column='transportationTypeId', on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.transportationtype')),
            ],
            options={
                'db_table': 'PlayerTransportationDetails',
            },
        ),
    ]
