# Generated by Django 5.2.4 on 2025-10-13 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0006_players_is_self_registered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='countryid',
            field=models.ForeignKey(blank=True, db_column='countryId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.countrymst'),
        ),
    ]
