# Generated by Django 5.2.7 on 2025-10-14 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0007_alter_players_countryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercomplaint',
            name='department',
            field=models.ForeignKey(db_column='departmentId', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.department'),
            preserve_default=False,
        ),
    ]
