# Generated by Django 5.2.7 on 2025-10-14 19:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0008_playercomplaint_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(default='WELCOME', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('html_content', models.TextField(blank=True, null=True)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('status_flag', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fwc.playerregistrationauditlog')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='fwc.players')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'db_table': 'email_log',
            },
        ),
        migrations.CreateModel(
            name='EnquiryDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_flag', models.IntegerField(default=1)),
                ('player', models.ForeignKey(db_column='playerId', on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.players')),
            ],
            options={
                'db_table': 'EnquiryDetails',
            },
        ),
    ]
