# Generated by Django 5.2.4 on 2025-10-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0008_announcements_playercomplaint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playercomplaint',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='playercomplaint',
            name='subject',
        ),
    ]
