# Generated by Django 5.2.4 on 2025-10-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0009_remove_playercomplaint_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='updated_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='playercomplaint',
            name='updated_on',
            field=models.DateTimeField(null=True),
        ),
    ]
