# Generated by Django 5.2.7 on 2025-10-15 16:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0009_emaillog_enquirydetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoginOtpVerification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobileno', models.BigIntegerField(null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('secureotp', models.CharField(max_length=256)),
                ('source', models.CharField(max_length=50, null=True)),
                ('flag', models.CharField(max_length=100, null=True)),
                ('device_id', models.TextField(max_length=500, null=True)),
                ('device_type', models.CharField(max_length=250, null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('user_type', models.CharField(max_length=50, null=True)),
                ('otp_expired_on', models.DateTimeField(null=True)),
                ('support_remarks', models.TextField(max_length=500, null=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_flag', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'PlayerLoginOtpVerification',
            },
        ),
        migrations.CreateModel(
            name='UserDeviceToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=200, null=True)),
                ('device_token', models.TextField(max_length=500, null=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_flag', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'UserDeviceToken',
            },
        ),
        migrations.AlterField(
            model_name='playertransportationdetails',
            name='status',
            field=models.CharField(blank=True, choices=[('ARRIVED_AIRPORT', 'Arrived at Airport'), ('ENTROUTE_HOTEL', 'Entroute to Hotel'), ('REACHED_HOTEL', 'Reached Hotel'), ('IN_TRANSIT', 'In Transit'), ('REACHED_DESTINATION', 'Reached Destination'), ('DEPARTED_AIRPORT', 'Departed for Airport'), ('REACHED_AIRPORT_DEPARTURE', 'Reached Airport for Departure')], default='IN_TRANSIT', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Roaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vechicle_no', models.CharField(max_length=100, null=True)),
                ('vechicle_type', models.TextField(null=True)),
                ('number_of_seats', models.IntegerField(null=True)),
                ('driver_name', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('ARRIVED_AIRPORT', 'Arrived at Airport'), ('ENTROUTE_HOTEL', 'Entroute to Hotel'), ('REACHED_HOTEL', 'Reached Hotel'), ('IN_TRANSIT', 'In Transit'), ('REACHED_DESTINATION', 'Reached Destination'), ('DEPARTED_AIRPORT', 'Departed for Airport'), ('REACHED_AIRPORT_DEPARTURE', 'Reached Airport for Departure')], default='IN_TRANSIT', max_length=200, null=True)),
                ('status_flag', models.IntegerField(default=1)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('transportationTypeId', models.ForeignKey(db_column='transportationTypeId', on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.transportationtype')),
            ],
            options={
                'db_table': 'Roaster',
            },
        ),
        migrations.AddField(
            model_name='playertransportationdetails',
            name='roasterId',
            field=models.ForeignKey(blank=True, db_column='roasterId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.roaster'),
        ),
    ]
