# Generated by Django 5.2.7 on 2025-10-15 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0010_customerloginotpverification_userdevicetoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roaster',
            name='travel_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='playertransportationdetails',
            name='details',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='playertransportationdetails',
            name='drop_location',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='playertransportationdetails',
            name='pickup_location',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='playertransportationdetails',
            name='remarks',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='playertransportationdetails',
            name='transportationTypeId',
            field=models.ForeignKey(db_column='transportationTypeId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.transportationtype'),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='driver_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='number_of_seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='vechicle_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='vechicle_type',
            field=models.TextField(),
        ),
    ]
