# Generated by Django 5.2.4 on 2025-10-11 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0010_alter_announcements_updated_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementrecipients',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='announcementrecipients',
            name='read_on',
        ),
    ]
