# Generated by Django 5.2.7 on 2025-10-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0011_roaster_travel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roaster',
            name='travel_date',
            field=models.DateTimeField(null=True),
        ),
    ]
