# Generated by Django 5.2.4 on 2025-10-11 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0011_remove_announcementrecipients_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementrecipients',
            name='announcement',
            field=models.ForeignKey(db_column='announcementId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipients', to='fwc.announcements'),
        ),
        migrations.AlterField(
            model_name='announcementrecipients',
            name='player',
            field=models.ForeignKey(db_column='playerId', on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.players'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.mstuserlogins'),
        ),
        migrations.AlterField(
            model_name='citymst',
            name='state_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.statemst'),
        ),
        migrations.AlterField(
            model_name='mstuserlogins',
            name='roleid',
            field=models.ForeignKey(db_column='roleId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.mstrole'),
        ),
        migrations.AlterField(
            model_name='playercomplaint',
            name='player',
            field=models.ForeignKey(db_column='playerId', on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.players'),
        ),
        migrations.AlterField(
            model_name='playercomplaintconversation',
            name='complaint',
            field=models.ForeignKey(db_column='complaintId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='conversations', to='fwc.playercomplaint'),
        ),
        migrations.AlterField(
            model_name='playercomplaintconversation',
            name='sender_player',
            field=models.ForeignKey(blank=True, db_column='senderPlayerId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.players'),
        ),
        migrations.AlterField(
            model_name='playercomplaintconversation',
            name='sender_user',
            field=models.ForeignKey(blank=True, db_column='senderUserId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.mstuserlogins'),
        ),
    ]
