# Generated by Django 5.2.7 on 2025-10-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0012_alter_roaster_travel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='accompanying_person',
            field=models.TextField(null=True),
        ),
    ]
