# Generated by Django 5.2.7 on 2025-10-15 21:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0013_players_accompanying_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='accompanying_person',
            new_name='accompanying_persons',
        ),
        migrations.CreateModel(
            name='PlayerDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_document', models.FileField(upload_to='player_reg_documents/')),
                ('document_type', models.CharField(default='IDENTIFICATION', max_length=100)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_flag', models.IntegerField(default=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_documents', to='fwc.players')),
            ],
            options={
                'db_table': 'PlayerDocument',
            },
        ),
    ]
