# Generated by Django 5.2.7 on 2025-10-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0014_rename_accompanying_person_players_accompanying_persons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerregistrationauditlog',
            name='accompanying_persons',
            field=models.TextField(null=True),
        ),
    ]
