# Generated by Django 5.2.7 on 2025-10-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0015_playerregistrationauditlog_accompanying_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roaster',
            name='status',
        ),
        migrations.RemoveField(
            model_name='roaster',
            name='travel_date',
        ),
        migrations.AddField(
            model_name='playertransportationdetails',
            name='travel_date',
            field=models.DateTimeField(null=True),
        ),
    ]
