# Generated by Django 5.2.7 on 2025-10-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0016_remove_roaster_status_remove_roaster_travel_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertransportationdetails',
            name='status_flag',
            field=models.IntegerField(default=1),
        ),
    ]
