# Generated by Django 5.2.7 on 2025-10-16 20:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0017_playertransportationdetails_status_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetInTouch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('subject', models.CharField(max_length=500, null=True)),
                ('message', models.TextField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_flag', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'GetInTouch',
            },
        ),
    ]
