# Generated by Django 5.2.7 on 2025-10-16 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0018_getintouch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GetInTouch',
            new_name='ContactUs',
        ),
        migrations.AlterModelTable(
            name='contactus',
            table='ContactUs',
        ),
    ]
