# Generated by Django 5.2.7 on 2025-10-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0019_rename_getintouch_contactus_alter_contactus_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydetails',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
