# Generated by Django 5.2.7 on 2025-10-17 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0020_enquirydetails_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='arrival_airport',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='arrival_flight_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='arrival_flight_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='departure_airport',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='departure_flight_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='departure_flight_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mstuserlogins',
            name='roleid',
            field=models.ForeignKey(db_column='roleId', on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.mstrole'),
        ),
    ]
