# Generated by Django 5.2.7 on 2025-10-20 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0021_players_arrival_airport_players_arrival_flight_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='arrival_fight_no',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='departure_fight_no',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='PlayerEnquiryResponses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rnquiry_response', models.TextField()),
                ('player', models.ForeignKey(db_column='playerId', on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.players')),
            ],
            options={
                'db_table': 'PlayerEnquiryResponses',
            },
        ),
    ]
