# Generated by Django 5.2.7 on 2025-10-20 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0022_players_arrival_fight_no_players_departure_fight_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerenquiryresponses',
            name='enquiry',
            field=models.ForeignKey(db_column='enquiryId', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.enquirydetails'),
            preserve_default=False,
        ),
    ]
