# Generated by Django 5.2.7 on 2025-10-20 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0023_playerenquiryresponses_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerenquiryresponses',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='playerenquiryresponses',
            name='status_flag',
            field=models.IntegerField(default=1),
        ),
    ]
