# Generated by Django 5.2.7 on 2025-10-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0024_playerenquiryresponses_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydetails',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
    ]
