# Generated by Django 5.2.7 on 2025-10-20 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0025_enquirydetails_is_replied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquirydetails',
            name='response',
        ),
        migrations.AddField(
            model_name='playerenquiryresponses',
            name='user',
            field=models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.mstuserlogins'),
        ),
        migrations.AlterField(
            model_name='playerenquiryresponses',
            name='player',
            field=models.ForeignKey(blank=True, db_column='playerId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.players'),
        ),
    ]
