# Generated by Django 5.2.7 on 2025-10-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0026_remove_enquirydetails_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquirydetails',
            name='is_replied',
        ),
    ]
