# Generated by Django 5.2.7 on 2025-10-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0027_remove_enquirydetails_is_replied'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydetails',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
    ]
