# Generated by Django 5.2.7 on 2025-10-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0028_enquirydetails_is_replied'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='transport_status',
            field=models.CharField(blank=True, choices=[('ARRIVED_AIRPORT', 'Arrived at Airport'), ('REACHED_AIRPORT_DEPARTURE', 'Reached Airport for Departure')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='playertransportationdetails',
            name='entry_status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('STARTED', 'Started'), ('ENDED', 'Ended')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='playertransportationdetails',
            name='drop_location',
            field=models.CharField(choices=[('AIRPORT_MOPA', 'Airport MOPA'), ('AIRPORT_DABOLIM', 'Airport Dabolim'), ('HOTEL', 'Hotel'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='playertransportationdetails',
            name='pickup_location',
            field=models.CharField(choices=[('AIRPORT_MOPA', 'Airport MOPA'), ('AIRPORT_DABOLIM', 'Airport Dabolim'), ('HOTEL', 'Hotel'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='playertransportationdetails',
            name='status',
            field=models.CharField(blank=True, choices=[('ARRIVED_AIRPORT', 'Arrived at Airport'), ('ENTROUTE_HOTEL', 'Enroute to Hotel'), ('REACHED_HOTEL', 'Reached Hotel'), ('IN_TRANSIT', 'In Transit'), ('REACHED_DESTINATION', 'Reached Destination'), ('DEPARTED_AIRPORT', 'Departed for Airport'), ('REACHED_AIRPORT_DEPARTURE', 'Reached Airport for Departure')], max_length=200, null=True),
        ),
    ]
