# Generated by Django 5.2.7 on 2025-10-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0029_players_transport_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertransportationdetails',
            name='drop_location_custom',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='playertransportationdetails',
            name='pickup_location_custom',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
