# Generated by Django 5.2.7 on 2025-10-21 14:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0030_playertransportationdetails_drop_location_custom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playertransportationdetails',
            name='status',
        ),
        migrations.AddField(
            model_name='roaster',
            name='mobile_no',
            field=models.BigIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='TransportStatusMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_location', models.CharField(choices=[('AIRPORT_MOPA', 'Airport MOPA'), ('AIRPORT_DABOLIM', 'Airport Dabolim'), ('HOTEL', 'Hotel'), ('OTHER', 'Other')], max_length=20)),
                ('drop_location', models.CharField(choices=[('AIRPORT_MOPA', 'Airport MOPA'), ('AIRPORT_DABOLIM', 'Airport Dabolim'), ('HOTEL', 'Hotel'), ('OTHER', 'Other')], max_length=20)),
                ('status_type', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('STARTED', 'Started'), ('ENDED', 'Ended')], max_length=20)),
                ('player_status', models.CharField(max_length=100)),
                ('status_flag', models.IntegerField(default=1)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'TransportStatusMapping',
                'unique_together': {('pickup_location', 'drop_location', 'status_type')},
            },
        ),
    ]
