# Generated by Django 5.2.7 on 2025-10-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0031_remove_playertransportationdetails_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transportstatusmapping',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='playertransportationdetails',
            name='drop_location',
            field=models.CharField(choices=[('AIRPORT_MOPA', 'Airport MOPA'), ('AIRPORT_DABOLIM', 'Airport Dabolim'), ('HOTEL', 'Hotel'), ('OTHER', 'Other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='playertransportationdetails',
            name='entry_status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('STARTED', 'Started'), ('ENDED', 'Ended'), ('ARRIVED_AIRPORT', 'Arrived at Airport'), ('REACHED_AIRPORT_DEPARTURE', 'Reached Airport for Departure')], default='SCHEDULED', max_length=100),
        ),
        migrations.AlterField(
            model_name='playertransportationdetails',
            name='pickup_location',
            field=models.CharField(choices=[('AIRPORT_MOPA', 'Airport MOPA'), ('AIRPORT_DABOLIM', 'Airport Dabolim'), ('HOTEL', 'Hotel'), ('OTHER', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transportstatusmapping',
            name='drop_location',
            field=models.CharField(choices=[('AIRPORT_MOPA', 'Airport MOPA'), ('AIRPORT_DABOLIM', 'Airport Dabolim'), ('HOTEL', 'Hotel'), ('OTHER', 'Other')], max_length=80),
        ),
        migrations.AlterField(
            model_name='transportstatusmapping',
            name='pickup_location',
            field=models.CharField(choices=[('AIRPORT_MOPA', 'Airport MOPA'), ('AIRPORT_DABOLIM', 'Airport Dabolim'), ('HOTEL', 'Hotel'), ('OTHER', 'Other')], max_length=80),
        ),
        migrations.AlterField(
            model_name='transportstatusmapping',
            name='player_status',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='transportstatusmapping',
            name='status_type',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('STARTED', 'Started'), ('ENDED', 'Ended')], max_length=80),
        ),
    ]
