# Generated by Django 5.2.7 on 2025-10-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0032_alter_transportstatusmapping_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportstatusmapping',
            name='status_type',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('STARTED', 'Started'), ('ENDED', 'Ended'), ('ARRIVED_AIRPORT', 'Arrived at Airport'), ('REACHED_AIRPORT_DEPARTURE', 'Reached Airport for Departure')], max_length=80),
        ),
    ]
