# Generated by Django 5.2.7 on 2025-10-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0033_alter_transportstatusmapping_status_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='hotel',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='room_no',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
