# Generated by Django 5.2.7 on 2025-10-22 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0034_players_hotel_players_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roaster',
            name='transportationTypeId',
            field=models.ForeignKey(blank=True, db_column='transportationTypeId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.transportationtype'),
        ),
    ]
