# Generated by Django 5.2.7 on 2025-10-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0035_alter_roaster_transportationtypeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playertransportationdetails',
            name='drop_location',
        ),
        migrations.RemoveField(
            model_name='playertransportationdetails',
            name='drop_location_custom',
        ),
        migrations.RemoveField(
            model_name='playertransportationdetails',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='playertransportationdetails',
            name='pickup_location_custom',
        ),
        migrations.AddField(
            model_name='roaster',
            name='drop_location',
            field=models.CharField(choices=[('AIRPORT_MOPA', 'Airport MOPA'), ('AIRPORT_DABOLIM', 'Airport Dabolim'), ('HOTEL', 'Hotel'), ('OTHER', 'Other')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='roaster',
            name='drop_location_custom',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='roaster',
            name='pickup_location',
            field=models.CharField(choices=[('AIRPORT_MOPA', 'Airport MOPA'), ('AIRPORT_DABOLIM', 'Airport Dabolim'), ('HOTEL', 'Hotel'), ('OTHER', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roaster',
            name='pickup_location_custom',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
