# Generated by Django 5.2.7 on 2025-10-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0036_remove_playertransportationdetails_drop_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playertransportationdetails',
            name='travel_date',
        ),
        migrations.AddField(
            model_name='roaster',
            name='travel_date',
            field=models.DateTimeField(null=True),
        ),
    ]
