# Generated by Django 5.2.7 on 2025-10-22 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0037_remove_playertransportationdetails_travel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertransportationdetails',
            name='details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='playertransportationdetails',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='playertransportationdetails',
            name='transportationTypeId',
            field=models.ForeignKey(blank=True, db_column='transportationTypeId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fwc.transportationtype'),
        ),
        migrations.AlterField(
            model_name='playertransportationdetails',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playertransportationdetails',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='drop_location',
            field=models.CharField(blank=True, choices=[('AIRPORT_MOPA', 'Airport MOPA'), ('AIRPORT_DABOLIM', 'Airport Dabolim'), ('HOTEL', 'Hotel'), ('OTHER', 'Other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='mobile_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='pickup_location',
            field=models.CharField(blank=True, choices=[('AIRPORT_MOPA', 'Airport MOPA'), ('AIRPORT_DABOLIM', 'Airport Dabolim'), ('HOTEL', 'Hotel'), ('OTHER', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportstatusmapping',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportstatusmapping',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
