# Generated by Django 5.2.7 on 2025-10-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0038_alter_playertransportationdetails_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(default='WELCOME', max_length=60),
        ),
    ]
