# Generated by Django 5.2.7 on 2025-10-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0039_alter_emaillog_email_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='notification_read_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
