# Generated by Django 5.2.7 on 2025-10-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0040_players_notification_read_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
