# Generated by Django 5.2.7 on 2025-10-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0041_announcements_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roaster',
            name='number_of_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
