# Generated by Django 5.2.7 on 2025-10-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0042_alter_roaster_number_of_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevicetoken',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
