# Generated by Django 5.2.7 on 2025-10-27 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0043_userdevicetoken_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdevicetoken',
            old_name='type',
            new_name='device_type',
        ),
    ]
