# Generated by Django 5.2.7 on 2025-10-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0044_rename_type_userdevicetoken_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='loginname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
