# Generated by Django 5.2.7 on 2025-10-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwc', '0045_alter_players_loginname'),
    ]

    operations = [
        migrations.AddField(
            model_name='roaster',
            name='is_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
