import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

RFAPI_USERNAME = os.getenv('API_USERNAME')
RFAPI_PASSWORD = os.getenv('API_PASSWORD')

KX_SMS_API_KEY = os.getenv('KX_SMS_API_SECRET_KEY')

CRM_APP_API_RF_USERNAME = os.getenv('CRM_APP_API_RF_USERNAME')
CRM_APP_API_RF_PASSWORD = os.getenv('CRM_APP_API_RF_PASSWORD')

SCHEDULE_LOGGER_NAME = os.getenv('SCHEDULE_LOGGER_NAME')
SCHEDULE_LOG_FILE_NAME = os.getenv('SCHEDULE_LOG_FILE_NAME')
SCHEDULE_LOG_FILE_FORMAT =os.getenv('SCHEDULE_LOG_FILE_FORMAT')
SCHEDULE_LOGGING_LEVEL = os.getenv('SCHEDULE_LOGGING_LEVEL')

RECAPTCHA_SITE_KEY = os.getenv('RECAPTCHA_SITE_KEY')
RECAPTCHA_SECRET_KEY = os.getenv('RECAPTCHA_SECRET_KEY')



