import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

FWC_APP_API_USERNAME = os.getenv('API_USERNAME')
FWC_APP_API_PASSWORD = os.getenv('API_PASSWORD')

SCHEDULE_LOGGER_NAME = os.getenv('SCHEDULE_LOGGER_NAME')
SCHEDULE_LOG_FILE_NAME = os.getenv('SCHEDULE_LOG_FILE_NAME')
SCHEDULE_LOG_FILE_FORMAT =os.getenv('SCHEDULE_LOG_FILE_FORMAT')
SCHEDULE_LOGGING_LEVEL = os.getenv('SCHEDULE_LOGGING_LEVEL')

RECAPTCHA_SITE_KEY = os.getenv('RECAPTCHA_SITE_KEY')
RECAPTCHA_SECRET_KEY = os.getenv('RECAPTCHA_SECRET_KEY')

CHESS_FWC_2025_EMAIL = os.getenv('CHESS_FWC_2025_EMAIL')

TYPE = os.getenv('TYPE')
PROJECT_ID=os.getenv('PROJECT_ID')
PRIVATE_KEY_ID=os.getenv('PRIVATE_KEY_ID')
PRIVATE_KEY=os.getenv('PRIVATE_KEY')
CLIENT_EMAIL=os.getenv('CLIENT_EMAIL')
CLIENT_ID=os.getenv('CLIENT_ID')
AUTH_URL=os.getenv('AUTH_URL')
TOKEN_URL=os.getenv('TOKEN_URL')
AUTH_PROVIDER_X509_CERT_URL=os.getenv('AUTH_PROVIDER_X509_CERT_URL')
CLIENT_X509_CERT_URL=os.getenv('CLIENT_X509_CERT_URL')
UNIVERSE_DOMAIN=os.getenv('UNIVERSE_DOMAIN')
NOTIFICATION_STATUS=os.getenv('NOTIFICATION_STATUS')



